<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <AssemblyTitle>CommonPlugin</AssemblyTitle>
        <Product>CommonPlugin</Product>
        <Copyright>Copyright © 2024</Copyright>
        <OutputPath>bin\$(Configuration)\</OutputPath>
        <UseWPF>true</UseWPF>
        <LangVersion>default</LangVersion>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AdysTech.CredentialManager" Version="3.1.0"/>
        <PackageReference Include="ByteSize" Version="2.1.2"/>
        <PackageReference Include="CliWrap" Version="3.10.5"/>
        <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
        <PackageReference Include="Linguini.Bundle" Version="0.11.0"/>
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Playnite.SDK" Version="11.0.0-alpha14"/>
    </ItemGroup>
    <ItemGroup Label="compileInclude3p">
        <Compile Include="..\third_party\Playnite_mod\**\*.cs">
            <Link>Shared\Playnite_mod\%(RecursiveDir)\%(Filename)%(Extension)</Link>
        </Compile>
    </ItemGroup>
</Project>